export { definePlugin } from './define-plugin.js';
export { MaydayPluginUI } from './ui.js';

// Re-export commonly used types for plugin authors
export type {
  PluginContext,
  PluginDefinition,
  PluginManifest,
  PluginCommand,
  PluginLogger,
  PluginDataStore,
  PluginUI,
  PluginServices,
  TimelineServiceAPI,
  AIServiceAPI,
  MediaServiceAPI,
  AICompletionOptions,
  SilenceDetectionOptions,
  Sequence,
  Clip,
  Marker,
  Track,
  MarkerColor,
  MediaMetadata,
  SilentRegion,
  EditType,
  EditDetectedEvent,
  ProjectBinItem,
  EffectsServiceAPI,
  EffectPreset,
  EffectCaptureResult,
  EffectApplyResult,
  CapturedEffect,
  EffectProperty,
  EffectKeyframe,
  PresetIndexEntry,
  PresetLibraryIndex,
  PresetFolder,
  ExcaliburPresetCommand,
} from '@mayday/types';
