import type { PresetIndexEntry, ExcaliburPresetCommand } from '@mayday/types';

const DEFAULT_PORT = 9876;

function curlCommand(presetId: string, port = DEFAULT_PORT): string {
  if (!/^[a-f0-9-]+$/i.test(presetId)) {
    throw new Error(`Invalid presetId: ${presetId}`);
  }
  return `curl -s -X POST http://localhost:${port}/api/plugins/preset-vault/command/apply -H "Content-Type: application/json" -d "{\\"presetId\\":\\"${presetId}\\"}"`;
}

export function buildExcaliburCommands(presets: PresetIndexEntry[], port = DEFAULT_PORT): ExcaliburPresetCommand[] {
  return presets.map(p => ({
    presetId: p.id,
    presetName: p.name,
    curlCommand: curlCommand(p.id, port),
    description: `Apply "${p.name}" (${p.effectCount} effects) from ${p.sourceClipName}`,
  }));
}

export function generateExcaliburGuide(presets: PresetIndexEntry[], port = DEFAULT_PORT): string {
  const commands = buildExcaliburCommands(presets, port);
  let md = `# Excalibur User Commands — Preset Vault\n\n`;
  md += `These presets can be applied via Excalibur User Commands.\n`;
  md += `For each preset below, create a new User Command in Excalibur:\n\n`;
  md += `## Setup\n\n`;
  md += `1. Open Excalibur → Settings → User Commands\n`;
  md += `2. Click "Add Command"\n`;
  md += `3. Set Type to "Shell / Script"\n`;
  md += `4. Paste the command below\n`;
  md += `5. Assign a keyboard shortcut\n\n`;
  md += `## Presets\n\n`;

  for (const cmd of commands) {
    md += `### ${cmd.presetName}\n`;
    md += `${cmd.description}\n\n`;
    md += `\`\`\`\n${cmd.curlCommand}\n\`\`\`\n\n`;
  }

  return md;
}

export function generateAHKScript(presets: PresetIndexEntry[], port = DEFAULT_PORT): string {
  const commands = buildExcaliburCommands(presets, port);
  let script = `; Preset Vault — AutoHotkey Script\n`;
  script += `; Generated by Mayday Create\n`;
  script += `; Assign F-keys to presets\n\n`;
  script += `#Requires AutoHotkey v2.0\n\n`;

  const fKeys = ['F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24'];

  for (let i = 0; i < commands.length && i < fKeys.length; i++) {
    const cmd = commands[i];
    script += `; ${cmd.presetName} — ${cmd.description}\n`;
    script += `${fKeys[i]}::\n`;
    script += `{\n`;
    script += `    Run '${cmd.curlCommand.replace(/'/g, "''")}', , "Hide"\n`;
    script += `}\n\n`;
  }

  return script;
}

export function generateKeyboardMaestro(presets: PresetIndexEntry[], port = DEFAULT_PORT): string {
  const commands = buildExcaliburCommands(presets, port);
  let doc = `# Preset Vault — Keyboard Maestro Macros\n\n`;
  doc += `Create a new macro for each preset below.\n\n`;

  for (const cmd of commands) {
    doc += `## ${cmd.presetName}\n`;
    doc += `${cmd.description}\n\n`;
    doc += `**Action:** Execute Shell Script\n`;
    doc += `\`\`\`bash\n${cmd.curlCommand}\n\`\`\`\n\n`;
    doc += `**Trigger:** Assign your preferred hotkey\n\n---\n\n`;
  }

  return doc;
}
